
# _____                       _   _    _ _____
#|  __ \                     | | | |  | |_   _|
# | |__) |___ _ __   ___  _ __| |_| |  | | | |
# |  _  // _ \ '_ \ / _ \| '__| __| |  | | | |
# | | \ \  __/ |_) | (_) | |  | |_| |__| |_| |_
#|_|  \_\___| .__/ \___/|_|   \__|\____/|_____|
#| |        | |
#| |__  _   |_|
#| '_ \| | | |
#| |_) | |_| |
#|_.__/ \__, | _              _            __ ___
#    /\  __/ || |            | |          /_ |__ \
#   /  \|___/_| |__   ___  __| | ___  _ __ | |  ) |
#  / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
#/_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|

# Config here the form
Form:
  Title: "§2ReportUI"
  Content: "§fQui veux-tu report et pour qu'elle raison ?"
  Input: "§eR§ca§ei§cs§eo§cn §edu §er§ce§ep§co§er§ct"

# Config here the message when people will be report

Message:
  ServerMessage: "{TargetPlayerName} has been reported by {playerName} for {reason}"
  ConfirmMessage: "You have report {playerName}"

# Configure here the webhook message for discord | set "" if you want nothing
WebHook:
  Url: ""
  Description: ""
  Color: "16574595"
  Footer: ""
  ImageUrl: ""
  Title: "A new report has been send"
  Field:
    1: "Reported player"
    2: "Reported by"
    3: "Reason :"